from colorama import Fore, Style, init
init()
import time

# init() is a function of library 
# "Fore" (Colorama) is used for Coloring 

print(Fore.CYAN + "=" * 60)
print("Welcome to Indian RTO Lookup".center(60))
print("=" * 60)
print("🇮🇳 INDIAN RTO CODE LOOKUP SYSTEM 🇮🇳".center(60))
print("=" * 60)
print("🚗 Find the location of any Indian RTO Code".center(60))
print("=" * 60)

print(Fore.BLUE + """
╔════════════════════════════╗
║      RTO LOOKUP MENU       ║
╠════════════════════════════╣
║ 1. Search RTO Code         ║
║ 2. View State Codes        ║
║ 3. Exit                    ║
╚════════════════════════════╝
""")

print(Style.RESET_ALL)

print("📝 Note: If you want to know about TELENGANA then use TG instead of TS\n")

state = {
# State Short Form for RTO
    "Maharastra" : "MH",
    "Punjab" : "PB",
    "Delhi" : "DL",
    "Uttar Pradesh" : "UP",
    "Rajasthan" : "RJ",
    "Haryana" : "HR",
    "Madhya Pradesh" : "MP",
    "Andhra Pradesh" : "AP",
    "Arunachal Pradesh" : "AR",
    "Assam" : "AS",
    "Chhattisgarh" : "CG",
    "Gujarat" : "GJ",
    "Bihar" : "BR",
    "Jharkhand" : "JH",
    "Karnataka" : "KA",
    "Kerala" : "KL",
    "Tamil Nadu" : "TN",
    "Telangana" : "TG",
    "Odisha" : "OD",
    "West Bengal" : "WB",
    "Goa" : "GA",
    "Himachal Pradesh" : "HP",
    "Jammu and Kashmir" : "JK",
    "Uttarakhand" : "UK",
    "Chandigarh" : "CH",
    "Puducherry" : "PY",
    "Nagaland" : "NL",
    "Mizoram" : "MZ",
    "Manipur" : "MN",
    "Meghalaya" : "ML",
    "Sikkim" : "SK",
    "Tripura" : "TR",
    "Andaman and Nicobar Islands" : "AN",
    "Lakshadweep" : "LD", 
    "Ladakh" : "LA",
}

# If user want to know Short forms of state

n = input("Do you want to know about the short form of State? (yes/no): ")
if n.strip().lower() == "yes":
    for state, code in state.items():
        print(f"{state:<30} {code}")

rto = {
    # Telangana RTO Codes
    "TG-01" : "Adilabad",
    "TG-02" : "Karimnagar",
    "TG-03" : "Warangal Urban",
    "TG-04" : "Khammam",
    "TG-05" : "Nalgonda",
    "TG-06" : "Mahabubnagar",
    "TG-07" : "Rangareddy",
    "TG-08" : "Medchal-Malkajgiri",
    "TG-09" : "Hyderabad Central",
    "TG-10" : "Hyderabad North",
    "TG-11" : "Hyderabad East",
    "TG-12" : "Hyderabad South",
    "TG-13" : "Hyderabad West",
    "TG-14" : "Reserved (Hyderabad)",
    "TG-15" : "Sangareddy",
    "TG-16" : "Nizamabad",
    "TG-17" : "Kamareddy",
    "TG-18" : "Nirmal",
    "TG-19" : "Mancherial",
    "TG-20" : "Komaram Bheem Asifabad",
    "TG-21" : "Jagtial",
    "TG-22" : "Peddapalli",
    "TG-23" : "Rajanna Sircilla",
    "TG-24" : "Warangal Rural",
    "TG-25" : "Jayashankar Bhupalpally",
    "TG-26" : "Mahabubabad",
    "TG-27" : "Jangaon",
    "TG-28" : "Bhadradri Kothagudem",
    "TG-29" : "Suryapet",
    "TG-30" : "Yadadri Bhuvanagiri",
    "TG-31" : "Nagarkurnool",
    "TG-32" : "Wanaparthy",
    "TG-33" : "Jogulamba Gadwal",
    "TG-34" : "Vikarabad",
    "TG-35" : "Medak",
    "TG-36" : "Siddipet",
    "TG-37" : "Mulugu",
    "TG-38" : "Narayanpet",

# Maharashtra RTO Codes

    "MH-02" : "Mumbai (West)",
    "MH-03" : "Mumbai (East)",
    "MH-04" : "Thane",
    "MH-05" : "Kalyan",
    "MH-06" : "Raigad (Pen)",
    "MH-07" : "Sindhudurg",
    "MH-08" : "Ratnagiri",
    "MH-09" : "Kolhapur",
    "MH-10" : "Sangli",
    "MH-11" : "Satara",
    "MH-12" : "Pune",
    "MH-13" : "Solapur",
    "MH-14" : "Pimpri-Chinchwad",
    "MH-15" : "Nashik",
    "MH-16" : "Ahmednagar",
    "MH-17" : "Shrirampur",
    "MH-18" : "Dhule",
    "MH-19" : "Jalgaon",
    "MH-20" : "Aurangabad (Chhatrapati Sambhajinagar)",
    "MH-21" : "Jalna",
    "MH-22" : "Parbhani",
    "MH-23" : "Beed",
    "MH-24" : "Latur",
    "MH-25" : "Dharashiv (Osmanabad)",
    "MH-26" : "Nanded",
    "MH-27" : "Amravati",
    "MH-28" : "Buldhana",
    "MH-29" : "Yavatmal",
    "MH-30" : "Akola",
    "MH-31" : "Nagpur (Urban)",
    "MH-32" : "Wardha",
    "MH-33" : "Gadchiroli",
    "MH-34" : "Chandrapur",
    "MH-35" : "Gondia",
    "MH-36" : "Bhandara",
    "MH-37" : "Washim",
    "MH-38" : "Hingoli",
    "MH-39" : "Nandurbar",
    "MH-40" : "Nagpur (Rural/Wadi)",
    "MH-41" : "Malegaon",
    "MH-42" : "Baramati",
    "MH-43" : "Navi Mumbai",
    "MH-44" : "Ambejogai",
    "MH-45" : "Akluj",
    "MH-46" : "Panvel",
    "MH-47" : "Mumbai North",
    "MH-48" : "Vasai-Virar",
    "MH-49" : "Nagpur East",
    "MH-50" : "Karad",

# Punjab RTO Codes

    "PB-01" : "Chandigarh",
    "PB-02" : "Amritsar",
    "PB-03" : "Bathinda",
    "PB-04" : "Faridkot",
    "PB-05" : "Ferozepur",
    "PB-06" : "Gurdaspur",
    "PB-07" : "Hoshiarpur",
    "PB-08" : "Jalandhar",
    "PB-09" : "Kapurthala",
    "PB-10" : "Ludhiana",
    "PB-11" : "Patiala",
    "PB-12" : "Ropar (Rupnagar)",
    "PB-13" : "Sangrur",
    "PB-14" : "Ajnala",
    "PB-15" : "Abohar",
    "PB-16" : "Anandpur Sahib",
    "PB-17" : "Baba Bakala",
    "PB-18" : "Batala",
    "PB-19" : "Barnala",
    "PB-20" : "Balachaur",
    "PB-21" : "Dasuya",
    "PB-22" : "Fazilka",
    "PB-23" : "Fatehgarh Sahib",
    "PB-24" : "Garhshankar",
    "PB-25" : "Jagraon",
    "PB-26" : "Khanna",
    "PB-27" : "Kharar",
    "PB-28" : "Malerkotla",
    "PB-29" : "Moga",
    "PB-30" : "Muktsar",
    "PB-31" : "Mansa",
    "PB-32" : "Nawanshahr (SBS Nagar)",
    "PB-33" : "Nakodar",
    "PB-34" : "Nabha",
    "PB-35" : "Pathankot",
    "PB-36" : "Phagwara",
    "PB-37" : "Phillaur",
    "PB-38" : "Patti",
    "PB-39" : "Rajpura",
    "PB-40" : "Rampura Phul",
    "PB-41" : "Sultanpur Lodhi",
    "PB-42" : "Samana",
    "PB-43" : "Samrala",
    "PB-44" : "Sunam",
    "PB-45" : "Talwandi Sabo",
    "PB-46" : "Tarn Taran",
    "PB-47" : "Zira",
    "PB-48" : "Amloh",
    "PB-49" : "Khamanon",
    "PB-50" : "Budhlada",
    "PB-51" : "Sardulgarh",
    "PB-52" : "Bassi Pathana",
    "PB-53" : "Malout",
    "PB-54" : "Mukerian",
    "PB-55" : "Payal",
    "PB-56" : "Raikot",
    "PB-57" : "Bhulath",
    "PB-58" : "Dera Baba Nanak",
    "PB-59" : "Dhuri",
    "PB-60" : "Gidderbaha",
    "PB-61" : "Jalalabad",
    "PB-62" : "Jaitu",
    "PB-63" : "Khadoor Sahib",
    "PB-64" : "Moonak",
    "PB-65" : "Mohali (SAS Nagar)",
    "PB-66" : "Nihal Singh Wala",
    "PB-67" : "Shahkot",
    "PB-68" : "Dhar Kalan",
    "PB-69" : "Bagha Purana",
    "PB-70" : "Dera Bassi",
    "PB-71" : "Chamkaur Sahib",
    "PB-72" : "Patran",
    "PB-73" : "Tappa Mandi",
    "PB-74" : "Nangal",
    "PB-75" : "Lehragaga",
    "PB-76" : "Ahmedgarh",
    "PB-77" : "Guru Har Sahai",
    "PB-78" : "Banga",
    "PB-79" : "Kotkapura",
    "PB-80" : "Majitha",
    "PB-81" : "Sardulgarh (Additional)",
    "PB-82" : "Amargarh",

# Delhi RTO Codes

    "DL-01" : "Mall Road",
    "DL-02" : "Tilak Marg",
    "DL-03" : "Sheikh Sarai",
    "DL-04" : "Janakpuri",
    "DL-05" : "Loni Road",
    "DL-06" : "Sarai Kale Khan",
    "DL-07" : "Mayur Vihar",
    "DL-08" : "Wazirpur",
    "DL-09" : "Dwarka",
    "DL-10" : "Raja Garden",
    "DL-11" : "Rohini",
    "DL-12" : "Vasant Vihar",
    "DL-13" : "Surajmal Vihar",

# Uttar Pradesh RTO Codes

    "UP-11" : "Saharanpur",
    "UP-12" : "Muzaffarnagar",
    "UP-13" : "Bulandshahr",
    "UP-14" : "Ghaziabad",
    "UP-15" : "Meerut",
    "UP-16" : "Noida (Gautam Buddh Nagar)",
    "UP-17" : "Baghpat",
    "UP-19" : "Shamli",
    "UP-20" : "Bijnor",
    "UP-21" : "Moradabad",
    "UP-22" : "Rampur",
    "UP-23" : "Jyotiba Phule Nagar (Amroha)",
    "UP-24" : "Badaun",
    "UP-25" : "Bareilly",
    "UP-26" : "Pilibhit",
    "UP-27" : "Shahjahanpur",
    "UP-30" : "Hardoi",
    "UP-31" : "Lakhimpur Kheri",
    "UP-32" : "Lucknow",
    "UP-33" : "Raebareli",
    "UP-34" : "Sitapur",
    "UP-35" : "Unnao",
    "UP-36" : "Banda",
    "UP-37" : "Hamirpur",
    "UP-38" : "Jalaun (Orai)",
    "UP-40" : "Bahraich",
    "UP-41" : "Barabanki",
    "UP-42" : "Faizabad (Ayodhya)",
    "UP-43" : "Gonda",
    "UP-44" : "Sultanpur",
    "UP-45" : "Ambedkar Nagar",
    "UP-46" : "Shravasti",
    "UP-47" : "Balrampur",
    "UP-50" : "Azamgarh",
    "UP-51" : "Basti",
    "UP-52" : "Deoria",
    "UP-53" : "Gorakhpur",
    "UP-54" : "Mau",
    "UP-55" : "Siddharthnagar",
    "UP-56" : "Maharajganj",
    "UP-57" : "Padrauna (Kushinagar)",
    "UP-58" : "Sant Kabir Nagar",
    "UP-60" : "Ballia",
    "UP-61" : "Ghazipur",
    "UP-62" : "Jaunpur",
    "UP-63" : "Mirzapur",
    "UP-64" : "Sonbhadra",
    "UP-65" : "Varanasi",
    "UP-66" : "Bhadohi (Sant Ravidas Nagar)",
    "UP-67" : "Chandauli",
    "UP-70" : "Allahabad (Prayagraj)",
    "UP-71" : "Fatehpur",
    "UP-72" : "Pratapgarh",
    "UP-73" : "Kaushambi",
    "UP-74" : "Kannauj",
    "UP-75" : "Etawah",
    "UP-76" : "Farrukhabad",
    "UP-77" : "Kanpur Dehat",
    "UP-78" : "Kanpur Nagar",
    "UP-79" : "Auraiya",
    "UP-80" : "Agra",
    "UP-81" : "Aligarh",
    "UP-82" : "Etah",
    "UP-83" : "Firozabad",
    "UP-84" : "Mainpuri",
    "UP-85" : "Mathura",
    "UP-86" : "Mahamaya Nagar (Hathras)",
    "UP-87" : "Kanshiram Nagar (Kasganj)",
    "UP-90" : "Banda",
    "UP-91" : "Hamirpur",
    "UP-92" : "Jalaun",
    "UP-93" : "Jhansi",
    "UP-94" : "Lalitpur",
    "UP-95" : "Mahoba",
    "UP-96" : "Chitrakoot",

# Rajasthan RTO Codes

    "RJ-01" : "Ajmer",
    "RJ-02" : "Alwar",
    "RJ-03" : "Banswara",
    "RJ-04" : "Barmer",
    "RJ-05" : "Bharatpur",
    "RJ-06" : "Bhilwara",
    "RJ-07" : "Bikaner",
    "RJ-08" : "Bundi",
    "RJ-09" : "Chittorgarh",
    "RJ-10" : "Churu",
    "RJ-11"	: "Dholpur",
    "RJ-12" : "Dungarpur",
    "RJ-13" : "Sri Ganganagar",
    "RJ-14" : "Jaipur",
    "RJ-15" : "Jaisalmer",
    "RJ-16" : "Jalore",
    "RJ-17" : "Jhalawar",
    "RJ-18" : "Jhunjhunu",
    "RJ-19" : "Jodhpur",
    "RJ-20" : "Kota",
    "RJ-21" : "Nagaur",
    "RJ-22" : "Pali",
    "RJ-23" : "Sikar",
    "RJ-24" : "Sirohi",
    "RJ-25" : "Sawai Madhopur",
    "RJ-26" : "Tonk",
    "RJ-27" : "Udaipur",
    "RJ-28" : "Baran",
    "RJ-29" : "Dausa",
    "RJ-30" : "Rajsamand",
    "RJ-31" : "Hanumangarh",
    "RJ-32" : "Kotputli-Behror (earlier Kotputli region)",
    "RJ-33" : "Karauli",
    "RJ-34" : "Pratapgarh",
    "RJ-35" : "Jaipur (Additional RTO)",
    "RJ-36" : "Jodhpur (Additional RTO)",
    "RJ-37" : "Pali (Additional Office)",
    "RJ-38" : "Abu Road",
    "RJ-39" : "Balotra",
    "RJ-40" : "Bhiwadi",
    "RJ-41" : "Chomu",
    "RJ-42" : "Kishangarh",
    "RJ-43" : "Phalodi",
    "RJ-44" : "Sujangarh",
    "RJ-45" : "Jaipur North",
    "RJ-46" : "Bikaner North",
    "RJ-47" : "Dudu",
    "RJ-48" : "Didwana",
    "RJ-49" : "Beawar",
    "RJ-50" : "Deeg",
    "RJ-51" : "Shahpura",
    "RJ-52" : "Kekri",
    "RJ-53" : "Gangapur City",
    "RJ-54" : "Neem Ka Thana",
    "RJ-55" : "Sanchore",
    "RJ-56" : "Anupgarh",
    "RJ-57" : "Salumbar",
    "RJ-58" : "Jaipur Rural",
    "RJ-59" : "Jodhpur Rural",
    "RJ-60" : "Udaipur Rural",

# Haryana RTO Codes

    "HR-01" : "Ambala",
    "HR-02" : "Jagadhri (Yamunanagar)",
    "HR-03" : "Panchkula",
    "HR-04" : "Naraingarh",
    "HR-05" : "Karnal",
    "HR-06" : "Panipat",
    "HR-07" : "Kurukshetra (Thanesar)",
    "HR-08" : "Kaithal",
    "HR-09" : "Guhla",
    "HR-10" : "Sonipat",
    "HR-11" : "Gohana",
    "HR-12" : "Rohtak",
    "HR-13" : "Bahadurgarh",
    "HR-14" : "Jhajjar",
    "HR-15" : "Meham",
    "HR-16" : "Bhiwani",
    "HR-17" : "Siwani",
    "HR-18" : "Loharu",
    "HR-19" : "Charkhi Dadri",
    "HR-20" : "Hisar",
    "HR-21" : "Hansi",
    "HR-22" : "Fatehabad",
    "HR-23" : "Tohana",
    "HR-24" : "Sirsa",
    "HR-25" : "Dabwali",
    "HR-26" : "Gurugram",
    "HR-27" : "Nuh",
    "HR-28" : "Ferozepur Jhirka",
    "HR-29" : "Ballabgarh",
    "HR-30" : "Palwal",
    "HR-31" : "Jind",
    "HR-32" : "Narwana",
    "HR-33" : "Safidon",
    "HR-34" : "Mahendragarh",
    "HR-35" : "Narnaul",
    "HR-36" : "Rewari",
    "HR-37" : "Ambala Cantt",
    "HR-38" : "Faridabad",
    "HR-39" : "Hisar",
    "HR-40" : "Assandh",
    "HR-41" : "Pehowa",
    "HR-42" : "Ganaur",
    "HR-43" : "Kosli",
    "HR-44" : "Ellenabad",
    "HR-45" : "Karnal",
    "HR-46" : "Rohtak",
    "HR-47" : "Rewari",
    "HR-48" : "Tosham",
    "HR-49" : "Kalka",
    "HR-50" : "Hodal",
    "HR-51" : "Faridabad",
    "HR-52" : "Hathin",
    "HR-53" : "Adampur",
    "HR-54" : "Barara",
    "HR-55" : "Gurgaon (Commercial Vehicles)",
    "HR-56" : "Jind",
    "HR-57" : "Sirsa",
    "HR-58" : "Jagadhri",
    "HR-59" : "Ratia",
    "HR-60" : "Samalkha",
    "HR-61" : "Bhiwani (Commercial)",
    "HR-62" : "Fatehabad (Commercial)",
    "HR-63" : "Jhajjar (Commercial)",
    "HR-64" : "Kaithal (Commercial)",
    "HR-65" : "Kurukshetra (Commercial)",
    "HR-66" : "Narnaul (Commercial)",
    "HR-67" : "Panipat (Commercial)",
    "HR-68" : "Panchkula (Commercial)",
    "HR-69" : "Sonipat (Commercial)",
    "HR-70" : "Chandigarh (Transport Commissioner)",
    "HR-71" : "Bilaspur",
    "HR-72" : "Gurugram (South)",
    "HR-73" : "Palwal",
    "HR-74" : "Nuh (Mewat)",
    "HR-75" : "Indri",
    "HR-76" : "Pataudi",
    "HR-77" : "Beri",
    "HR-78" : "Shahabad Markanda",
    "HR-79" : "Kharkhoda",
    "HR-80" : "Barwala",
    "HR-81" : "Bawal",
    "HR-82" : "Kanina",
    "HR-83" : "Kalayat",
    "HR-84" : "Charkhi Dadri",
    "HR-85" : "Ambala Cantt (South)",
    "HR-86" : "Narnaund",
    "HR-87" : "_BADkhal (Faridabad South)",
    "HR-88" : "_Badhra",
    "HR-89" : "Badli",
    "HR-90" : "Uchana",
    "HR-91" : "Gharaunda",
    "HR-92" : "Radaur",
    "HR-93" : "Punhana",
    "HR-94" : "Kalanwali",
    "HR-95" : "Sampla",
    "HR-96" : "Tauru",
    "HR-97" : "Ladwa",
    "HR-99" : "Temporary Registration",

# Madhya Pradesh RTO Codes

    "MP-01" : "Governor Vehicles",
    "MP-02" : "Government Vehicles",
    "MP-03" : "Police Vehicles",
    "MP-04" : "Bhopal",
    "MP-05" : "Narmadapuram (Hoshangabad)",
    "MP-06" : "Morena",
    "MP-07" : "Gwalior",
    "MP-08" : "Guna",
    "MP-09" : "Indore",
    "MP-10" : "Khargone",
    "MP-11" : "Dhar",
    "MP-12" : "Khandwa",
    "MP-13" : "Ujjain",
    "MP-14" : "Mandsaur",
    "MP-15" : "Sagar",
    "MP-16" : "Chhatarpur",
    "MP-17" : "Rewa",
    "MP-18" : "Shahdol",
    "MP-19" : "Satna",
    "MP-20" : "Jabalpur",
    "MP-21" : "Katni",
    "MP-22" : "Seoni",
    "MP-23" : "Raipur (old allocation)",
    "MP-24" : "Durg (old allocation)",
    "MP-25" : "Jagdalpur (old allocation)",
    "MP-26" : "Bilaspur (old allocation)",
    "MP-27" : "Ambikapur (old allocation)",
    "MP-28" : "Chhindwara",
    "MP-29" : "Rajnandgaon (old allocation)",
    "MP-30" : "Bhind",
    "MP-31" : "Sheopur",
    "MP-32" : "Datia",
    "MP-33" : "Shivpuri",
    "MP-34" : "Damoh",
    "MP-35" : "Panna",
    "MP-36" : "Tikamgarh",
    "MP-37" : "Sehore",
    "MP-38" : "Raisen",
    "MP-39" : "Rajgarh",
    "MP-40" : "Vidisha",
    "MP-41" : "Dewas",
    "MP-42" : "Shajapur",
    "MP-43" : "Ratlam",
    "MP-44" : "Neemuch",
    "MP-45" : "Jhabua",
    "MP-46" : "Barwani",
    "MP-47" : "Harda",
    "MP-48" : "Betul",
    "MP-49" : "Narsinghpur",
    "MP-50" : "Balaghat",
    "MP-51" : "Mandla",
    "MP-52" : "Dindori",
    "MP-53" : "Sidhi",
    "MP-54" : "Umaria",
    "MP-55" : "Bagli (Dewas District)",
    "MP-56" : "Seoni Malwa",
    "MP-57" : "Multai",
    "MP-58" : "Waidhan (Singrauli Region)",
    "MP-59" : "Maihar",
    "MP-60" : "Kukshi",
    "MP-61" : "Gadarwara",
    "MP-62" : "Sanawad",
    "MP-63" : "Bhainsdehi",
    "MP-64" : "Semaria",
    "MP-65" : "Anuppur",
    "MP-66" : "Singrauli",
    "MP-67" : "Ashoknagar",
    "MP-68" : "Burhanpur",
    "MP-69" : "Alirajpur",
    "MP-70" : "Agar Malwa",
    "MP-71" : "Niwari",

# Andhra Pradesh RTO Codes

    "AP-01" : "Nirmal / Adilabad",
    "AP-02" : "nantapur",
    "AP-03" : "Tirupati (Chittoor)",
    "AP-04" : "Kadapa",
    "AP-05" : "Rajahmundry",
    "AP-06" : "Kakinada",
    "AP-07" : "Narasaraopet",
    "AP-08" : "Guntur",
    "AP-16" : "Vijayawada",
    "AP-17" : "Vijayawada",
    "AP-18" : "Vijayawada",
    "AP-19" : "Vijayawada",
    "AP-21" : "Kurnool",
    "AP-26" : "Nellore",
    "AP-27" : "Ongole",
    "AP-30" : "Srikakulam",
    "AP-31" : "Visakhapatnam",
    "AP-32" : "Visakhapatnam",

# Arunachal Pradesh RTO Codes

    "AR-01" : "Itanagar",
    "AR-02" : "Yupia (Papum Pare)",
    "AR-03" : "Tawang",
    "AR-04" : "Bomdila (West Kameng)",
    "AR-05" : "Seppa (East Kameng)",
    "AR-06" : "Ziro (Lower Subansiri)",
    "AR-07" : "Daporijo (Upper Subansiri)",
    "AR-08" : "Aalo / Along (West Siang)",
    "AR-09" : "Pasighat (East Siang)",
    "AR-10" : "Anini (Dibang Valley)",
    "AR-11" : "Tezu (Lohit)",
    "AR-12" : "Changlang",
    "AR-13" : "Khonsa (Tirap)",
    "AR-14" : "Yingkiong (Upper Siang)",
    "AR-15" : "Koloriang (Kurung Kumey)",
    "AR-16" : "Roing (Lower Dibang Valley)",
    "AR-17" : "Hawai (Anjaw)",
    "AR-18" : "Longding",
    "AR-19" : "Palin (Kra Daadi)",
    "AR-20" : "Namsai",
    "AR-21" : "Boleng (Siang)",
    "AR-22" : "Likabali (Lower Siang)",
    "AR-23" : "Raga (Kamle)",
    "AR-24" : "Pakke Kessang",
    "AR-25" : "Basar (Leparada)",
    "AR-26" : "Tato (Shi Yomi)",

# Assam RTO Codes

    "AS-01" : "Guwahati (Kamrup Metro)",
    "AS-02" : "Nagaon",
    "AS-03" : "Jorhat",
    "AS-04" : "Sivasagar (Sibsagar)",
    "AS-05" : "Golaghat",
    "AS-06" : "Dibrugarh",
    "AS-07" : "North Lakhimpur",
    "AS-08" : "Dima Hasao (North Cachar Hills)",
    "AS-09" : "Karbi Anglong",
    "AS-10" : "Karimganj",
    "AS-11" : "Silchar (Cachar)",
    "AS-12" : "Tezpur (Sonitpur)",
    "AS-13" : "Darrang",
    "AS-14" : "Nalbari",
    "AS-15" : "Barpeta",
    "AS-16" : "Kokrajhar",
    "AS-17" : "Dhubri",
    "AS-18" : "Goalpara",
    "AS-19" : "Bongaigaon",
    "AS-20" : "Assam State Transport Corporation (ASTC)",
    "AS-21" : "Morigaon (Marigaon)",
    "AS-22" : "Dhemaji",
    "AS-23" : "Tinsukia",
    "AS-24" : "Hailakandi",
    "AS-25" : "Kamrup Rural",
    "AS-26" : "Chirang",
    "AS-27" : "Udalguri",
    "AS-28" : "Baksa",
    "AS-29" : "Assam New Registration Series",
    "AS-30" : "Assam Police Vehicles",
    "AS-31" : "Hojai",
    "AS-32" : "Biswanath",
    "AS-33" : "Charaideo",
    "AS-34" : "South Salmara - Mankachar",

# Chattisgarh RTO Codes

    "CG-01" : "Governor / State Government Vehicles",
    "CG-02" : "Raipur",
    "CG-03" : "Durg",
    "CG-04" : "Rajnandgaon",
    "CG-05" : "Bilaspur",
    "CG-06" : "Korba",
    "CG-07" : "Raigarh",
    "CG-08" : "Jagdalpur (Bastar)",
    "CG-09" : "Ambikapur (Surguja)",
    "CG-10" : "Dhamtari",
    "CG-11" : "Jashpur",
    "CG-12" : "Janjgir-Champa",
    "CG-13" : "Mahasamund",
    "CG-14" : "Kanker",
    "CG-15" : "Kawardha (Kabirdham)",
    "CG-16" : "Koriya (Baikunthpur)",
    "CG-17" : "Dantewada",
    "CG-18" : "Bijapur",
    "CG-19" : "Narayanpur",
    "CG-20" : "Gariaband",
    "CG-21" : "Balod",
    "CG-22" : "Baloda Bazar",
    "CG-23" : "Balrampur",
    "CG-24" : "Bemetara",
    "CG-25" : "Sukma",
    "CG-26" : "Kondagaon",
    "CG-27" : "Mungeli",
    "CG-28" : "Surajpur",
    "CG-29" : "Balodabazar-Bhatapara",
    "CG-30" : "Gaurela-Pendra-Marwahi",

# Bihar RTO Codes
    
    "BR-01" : "Patna",
    "BR-02" : "Gaya",
    "BR-03" : "Bhojpur (Ara)",
    "BR-04" : "Chapra (Saran)",
    "BR-05" : "Motihari (East Champaran)",
    "BR-06" : "Muzaffarpur",
    "BR-07" : "Darbhanga",
    "BR-08" : "Munger",
    "BR-09" : "Begusarai",
    "BR-10" : "Bhagalpur",
    "BR-11" : "Purnia",
    "BR-12" : "Siwan",
    "BR-13" : "Saharsa",
    "BR-14" : "Madhepura",
    "BR-15" : "Madhubani",
    "BR-16" : "Nalanda (Bihar Sharif)",
    "BR-17" : "Nawada",
    "BR-18" : "Rohtas (Sasaram)",
    "BR-19" : "Jehanabad",
    "BR-20" : "Buxar",
    "BR-21" : "Kishanganj",
    "BR-22" : "Katihar",
    "BR-23" : "Araria",
    "BR-24" : "Supaul",
    "BR-25" : "Sitamarhi",
    "BR-26" : "Vaishali (Hajipur)",
    "BR-27" : "Sheohar",
    "BR-28" : "Jamui",
    "BR-29" : "West Champaran (Bettiah)",
    "BR-30" : "Samastipur",
    "BR-31" : "Khagaria",
    "BR-32" : "Banka",
    "BR-33" : "Lakhisarai",
    "BR-34" : "Sheikhpura",
    "BR-37" : "Kaimur (Bhabua)",
    "BR-38" : "Arwal",

# Goa RTO Codes

    "GA-01" : "Panaji (North Goa)",
    "GA-02" : "Margao (South Goa)",
    "GA-03" : "Mapusa",
    "GA-04" : "Bicholim",
    "GA-05" : "Ponda",
    "GA-06" : "Vasco da Gama",
    "GA-07" : "Panaji (Tiswadi)",
    "GA-08" : "Margao (Salcete)",
    "GA-09" : "Quepem",
    "GA-10" : "Canacona",
    "GA-11" : "Pernem",
    "GA-12" : "Dharbandora",

# Himachal Pradesh RTO Codes

    "HP-01" : "Shimla",
    "HP-02" : "Shimla",
    "HP-03" : "Shimla",
    "HP-04" : "Dharamshala",
    "HP-05" : "Mandi",
    "HP-06" : "Rampur",
    "HP-07" : "Shimla",
    "HP-08" : "Chaupal",
    "HP-09" : "Theog",
    "HP-10" : "Rohru",
    "HP-11" : "Arki",
    "HP-12" : "Nalagarh",
    "HP-13" : "Kandaghat",
    "HP-14" : "Solan",
    "HP-15" : "Parwanoo",
    "HP-16" : "Rajgarh",
    "HP-17" : "Paonta Sahib",
    "HP-18" : "Nahan",
    "HP-19" : "Amb",
    "HP-20" : "Una",
    "HP-21" : "Barsar",
    "HP-22" : "Hamirpur",
    "HP-23" : "Ghumarwin",
    "HP-24" : "Bilaspur",
    "HP-25" : "Kalpa",
    "HP-26" : "Nichar",
    "HP-27" : "Pooh",
    "HP-28" : "Sarkaghat",
    "HP-29" : "Jogindernagar",
    "HP-30" : "Karsog",
    "HP-31" : "Sundernagar",
    "HP-32" : "Gohar",
    "HP-33" : "Mandi Sadar",
    "HP-34" : "Kullu",
    "HP-35" : "Anni",
    "HP-36" : "Dehra",
    "HP-37" : "Palampur",
    "HP-38" : "Nurpur",
    "HP-39" : "Dharamshala",
    "HP-40" : "Kangra",
    "HP-41" : "Kaza",
    "HP-42" : "Keylong",
    "HP-43" : "Udaipur",
    "HP-44" : "Churah (Tissa)",
    "HP-45" : "Pangi",
    "HP-46" : "Bharmour",
    "HP-47" : "Dalhousie",
    "HP-48" : "Chamba",
    "HP-49" : "Banjar",
    "HP-50" : "Shimla (special series)",
    "HP-51" : "Shimla",
    "HP-52" : "Shimla",
    "HP-53" : "Baijnath",
    "HP-54" : "Jawali",
    "HP-55" : "Nadaun",
    "HP-56" : "Jaisinghpur",
    "HP-57" : "Chowari",
    "HP-58" : "Manali",
    "HP-59" : "Solan",
    "HP-60" : "Hamirpur",
    "HP-61" : "Kullu",
    "HP-62" : "Shimla",
    "HP-63" : "Shimla",
    "HP-64" : "Solan",
    "HP-65" : "Mandi",
    "HP-66" : "Kullu",
    "HP-67" : "Hamirpur",
    "HP-68" : "Kangra",
    "HP-69" : "Bilaspur",
    "HP-70" : "Bilaspur",
    "HP-71" : "Sirmaur",
    "HP-72" : "Una",
    "HP-73" : "Chamba",
    "HP-74" : "Bhoranj",
    "HP-75" : "Shimla",
    "HP-76" : "Paddhar",
    "HP-77" : "Dodra Kwar",
    "HP-78" : "Bangana",
    "HP-79" : "Sangrah",
    "HP-80" : "Haroli",
    "HP-81" : "Salooni",
    "HP-82" : "Balh",
    "HP-83" : "Jawalamukhi",
    "HP-84" : "Sujanpur",
    "HP-85" : "Shillai",
    "HP-86" : "Dharampur",
    "HP-87" : "Thunag",
    "HP-87AA" : "Bali Chowki",
    "HP-88" : "Fatehpur",
    "HP-89" : "Jhandutta",
    "HP-90" : "Shahpur",
    "HP-91" : "Naina Devi (Swarghat)",
    "HP-92" : "Rampur Bushahr",
    "HP-93" : "Nalagarh",
    "HP-94" : "Nagrota Bagwan",
    "HP-95" : "Kumarsain",
    "HP-96" : "Dheera",
    "HP-97" : "Indora",
    "HP-98" : "Kasauli",
    "HP-99" : "Kotkhai",

# Jammu and Kashmir RTO Codes

    "JK-01" : "Srinagar",
    "JK-02" : "Jammu",
    "JK-03" : "Anantnag",
    "JK-04" : "Budgam",
    "JK-05" : "Baramulla",
    "JK-06" : "Doda",
    "JK-07" : "Kargil",
    "JK-08" : "Kathua",
    "JK-09" : "Kupwara",
    "JK-10" : "Leh",
    "JK-11" : "Rajouri",
    "JK-12" : "Poonch",
    "JK-13" : "Pulwama",
    "JK-14" : "Udhampur",
    "JK-15" : "Bandipora",
    "JK-16" : "Ganderbal",
    "JK-17" : "Kishtwar",
    "JK-18" : "Kulgam",
    "JK-19" : "Ramban",
    "JK-20" : "Reasi",
    "JK-21" : "Samba",
    "JK-22" : "Shopian",

# Ladakh RTO Codes

    "LA-01" : "kargil",
    "LA-02" : "Leh",

# Jharkhand RTO Codes

    "JH-01" : "Ranchi",
    "JH-02" : "Hazaribagh",
    "JH-03" : "Daltonganj (Palamu)",
    "JH-04" : "Dumka",
    "JH-05" : "Jamshedpur",
    "JH-06" : "Chaibasa",
    "JH-07" : "Gumla",
    "JH-08" : "Lohardaga",
    "JH-09" : "Bokaro Steel City",
    "JH-10" : "Dhanbad",
    "JH-11" : "Giridih",
    "JH-12" : "Koderma",
    "JH-13" : "Chatra",
    "JH-14" : "Garhwa",
    "JH-15" : "Deoghar",
    "JH-16" : "Pakur",
    "JH-17" : "Godda",
    "JH-18" : "Sahibganj",
    "JH-19" : "Latehar",
    "JH-20" : "Simdega",
    "JH-21" : "Jamtara",
    "JH-22" : "Saraikela–Kharsawan",
    "JH-23" : "Khunti",
    "JH-24" : "Ramgarh",
    "JH-99" : "State Transport Authority (STA)",

# Karnataka RTO Codes

    "KA-01" : "Bengaluru Central (Koramangala)",
    "KA-02" : "Bengaluru West (Rajajinagar)",
    "KA-03" : "Bengaluru East (Indiranagar)",
    "KA-04" : "Bengaluru North (Yeshwanthpur)",
    "KA-05" : "Bengaluru South (Jayanagar)",
    "KA-06" : "Tumakuru",
    "KA-07" : "Kolar",
    "KA-08" : "KGF (Kolar Gold Fields)",
    "KA-09" : "Mysuru West",
    "KA-10" : "Chamarajanagar",
    "KA-11" : "Mandya",
    "KA-12" : "Madikeri (Kodagu)",
    "KA-13" : "Hassan",
    "KA-14" : "Shivamogga",
    "KA-15" : "Sagara",
    "KA-16" : "Chitradurga",
    "KA-17" : "Davanagere",
    "KA-18" : "Chikkamagaluru",
    "KA-19" : "Mangaluru",
    "KA-20" : "Udupi",
    "KA-21" : "Puttur",
    "KA-22" : "Belagavi",
    "KA-23" : "Chikkodi",
    "KA-24" : "Bailhongal",
    "KA-25" : "Dharwad",
    "KA-26" : "Gadag",
    "KA-27" : "Haveri",
    "KA-28" : "Vijayapura (Bijapur)",
    "KA-29" : "Bagalkote",
    "KA-30" : "Karwar",
    "KA-31" : "Sirsi",
    "KA-32" : "Kalaburagi (Gulbarga)",
    "KA-33" : "Yadgir",
    "KA-34" : "Ballari",
    "KA-35" : "Hosapete (Hospet)",
    "KA-36" : "Raichur",
    "KA-37" : "Koppal",
    "KA-38" : "Bidar",
    "KA-39" : "Bhalki",
    "KA-40" : "Chikkaballapur",
    "KA-41" : "Jnana Bharathi",
    "KA-42" : "Ramanagara",
    "KA-43" : "Devanahalli",
    "KA-44" : "Tiptur",
    "KA-45" : "Hunsur",
    "KA-46" : "Sakleshpur",
    "KA-47" : "Honnavar",
    "KA-48" : "Jamkhandi",
    "KA-49" : "Gokak",
    "KA-50" : "Yelahanka",
    "KA-51" : "Electronics City",
    "KA-52" : "Nelamangala",
    "KA-53" : "Krishnarajapuram",
    "KA-54" : "Nagamangala",
    "KA-55" : "Mysuru East",
    "KA-56" : "Basavakalyan",
    "KA-57" : "Shantinagar",
    "KA-58" : "Banashankari",
    "KA-59" : "Chandapura",
    "KA-60" : "RT Nagar",
    "KA-61" : "Marathahalli",
    "KA-62" : "Surathkal",
    "KA-63" : "Dharwad East (Hubballi)",
    "KA-64" : "Madhugiri",
    "KA-65" : "Dandeli",
    "KA-66" : "Tarikere",
    "KA-67" : "Chintamani",
    "KA-68" : "Ranebennur",
    "KA-69" : "Ramdurg",
    "KA-70" : "Bantwal",
    "KA-71" : "Athani",

# Kerala RTO Codes

    "KL-01" : "Thiruvananthapuram",
    "KL-02" : "Kollam",
    "KL-03" : "Pathanamthitta",
    "KL-04" : "Alappuzha",
    "KL-05" : "Kottayam",
    "KL-06" : "Idukki",
    "KL-07" : "Ernakulam",   
    "KL-08" : "Thrissur",
    "KL-09" : "Palakkad",
    "KL-10" : "Malappuram",
    "KL-11" : "Kozhikode",
    "KL-12" : "Wayanad",
    "KL-13" : "Kannur",
    "KL-14" : "Kasaragod",
    "KL-15" : "Kerala State Road Transport Corporation (KSRTC)",
    "KL-16" : "Attingal",
    "KL-17" : "Muvattupuzha",
    "KL-18" : "Vadakara",
    "KL-19" : "Parassala",
    "KL-20" : "Neyyattinkara",
    "KL-21" : "Nedumangad",
    "KL-22" : "Kazhakkoottam",
    "KL-23" : "Karunagappally",
    "KL-24" : "Kottarakkara",
    "KL-25" : "Punalur",
    "KL-26" : "Adoor",
    "KL-27" : "Tiruvalla",
    "KL-28" : "Mallappally",
    "KL-29" : "Kayamkulam",
    "KL-30" : "Chengannur",
    "KL-31" : "Mavelikkara",
    "KL-32" : "Cherthala",
    "KL-33" : "Changanassery",
    "KL-34" : "Kanjirappally",
    "KL-35" : "Pala",
    "KL-36" : "Vaikom",
    "KL-37" : "Vandiperiyar",
    "KL-38" : "Thodupuzha",
    "KL-39" : "Thripunithura",
    "KL-40" : "Perumbavoor",
    "KL-41" : "Aluva",
    "KL-42" : "North Paravur",
    "KL-43" : "Mattancherry",
    "KL-44" : "Kothamangalam",
    "KL-45" : "Irinjalakuda",
    "KL-46" : "Guruvayur",
    "KL-47" : "Kodungallur",
    "KL-48" : "Wadakkanchery",
    "KL-49" : "Alathur",
    "KL-50" : "Mannarkkad",
    "KL-51" : "Ottapalam",
    "KL-52" : "Pattambi",
    "KL-53" : "Perinthalmanna",
    "KL-54" : "Ponnani",
    "KL-55" : "Tirur",
    "KL-56" : "Koyilandy",
    "KL-57" : "Koduvally",
    "KL-58" : "Thalassery",
    "KL-59" : "Taliparamba",
    "KL-60" : "Kanhangad",
    "KL-61" : "Kunnathur",
    "KL-62" : "Ranni",
    "KL-63" : "Angamaly",
    "KL-64" : "Chalakudy",
    "KL-65" : "Tirurangadi",
    "KL-66" : "Kuttanad",
    "KL-67" : "Uzhavoor",
    "KL-68" : "Devikulam",
    "KL-69" : "Udumbanchola",
    "KL-70" : "Chittur",
    "KL-71" : "Nilambur",
    "KL-72" : "Mananthavady",
    "KL-73" : "Sulthan Bathery",
    "KL-74" : "Kattakkada",
    "KL-75" : "Thriprayar",
    "KL-76" : "Nanminda",
    "KL-77" : "Perambra",
    "KL-78" : "Iritty",
    "KL-79" : "Vellarikundu",
    "KL-80" : "Pathanapuram",
    "KL-81" : "Varkala",
    "KL-82" : "Chadayamangalam",
    "KL-83" : "Konni",
    "KL-84" : "Kondotty",
    "KL-85" : "Ramanattukara",
    "KL-86" : "Payyanur",

# Gujrat RTO Codes

    "GJ-01" : "Ahmedabad (West)",
    "GJ-02" : "Mehsana",
    "GJ-03" : "Rajkot",
    "GJ-04" : "Bhavnagar",
    "GJ-05" : "Surat",
    "GJ-06" : "Vadodara",
    "GJ-07" : "Nadiad (Kheda)",
    "GJ-08" : "Palanpur (Banaskantha)",
    "GJ-09" : "Himmatnagar (Sabarkantha)",
    "GJ-10" : "Jamnagar",
    "GJ-11" : "Junagadh",
    "GJ-12" : "Bhuj (Kutch)",
    "GJ-13" : "Surendranagar",
    "GJ-14" : "Amreli",
    "GJ-15" : "Valsad",
    "GJ-16" : "Bharuch",
    "GJ-17" : "Godhra (Panchmahal)",
    "GJ-18" : "Gandhinagar",
    "GJ-19" : "Bardoli",
    "GJ-20" : "Dahod",
    "GJ-21" : "Navsari",
    "GJ-22" : "Rajpipla (Narmada)",
    "GJ-23" : "Anand",
    "GJ-24" : "Patan",
    "GJ-25" : "Porbandar",
    "GJ-26" : "Vyara (Tapi)",
    "GJ-27" : "Ahmedabad (East)",
    "GJ-28" : "Surat (Rural)",
    "GJ-29" : "Vadodara (Rural)",
    "GJ-30" : "Ahwa (Dang)",
    "GJ-31" : "Modasa (Aravalli)",
    "GJ-32" : "Veraval (Gir Somnath)",
    "GJ-33" : "Botad",
    "GJ-34" : "Chhota Udepur",
    "GJ-35" : "Lunawada (Mahisagar)",
    "GJ-36" : "Morbi",
    "GJ-37" : "Khambhaliya (Devbhoomi Dwarka)",
    "GJ-38" : "Bavla (Ahmedabad Rural)",

# Manipur RTO Codes

    "MN-01" : "Imphal East",
    "MN-02" : "Imphal West",
    "MN-03" : "Thoubal",
    "MN-04" : "Bishnupur",
    "MN-05" : "Ukhrul",
    "MN-06" : "Churachandpur",
    "MN-07" : "Senapati",
    "MN-08" : "Tamenglong",
    "MN-09" : "Chandel",
    "MN-10" : "Jiribam",
    "MN-11" : "Kakching",
    "MN-12" : "Tengnoupal",
    "MN-13" : "Kamjong",
    "MN-14" : "Noney",
    "MN-15" : "Pherzawl",

# Meghalaya RTO Codes

    "ML-01" : "Shillong",
    "ML-02" : "Jowai",
    "ML-03" : "Tura",
    "ML-04" : "Nongpoh",
    "ML-05" : "Williamnagar",
    "ML-06" : "Nongstoin",
    "ML-07" : "Baghmara",
    "ML-08" : "Mawkyrwat",
    "ML-09" : "Resubelpara",
    "ML-10" : "Ampati",
    "ML-11" : "Khliehriat",
    "ML-12" : "Eastern West Khasi Hills",
    "ML-13" : "Eastern West Garo Hills",
    "ML-14" : "South West Khasi Hills",
    "ML-15" : "South West Garo Hills",

# Mizoram RTO Codes

    "MZ-01" : "Aizawl",
    "MZ-02" : "Lunglei",
    "MZ-03" : "Saiha",
    "MZ-04" : "Champhai",
    "MZ-05" : "Kolasib",
    "MZ-06" : "Serchhip",
    "MZ-07" : "Lawngtlai",
    "MZ-08" : "Mamit",
    "MZ-09" : "Siaha",
    "MZ-10" : "Khawzawl",
    "MZ-11" : "Hnahthial",
    "MZ-12" : "Saitual",

# Nagaland RTO Codes

    "NL-01" : "Kohima",
    "NL-02" : "Mokokchung",
    "NL-03" : "Tuensang",
    "NL-04" : "Mon",
    "NL-05" : "Wokha",
    "NL-06" : "Zunheboto",  
    "NL-07" : "Dimapur",
    "NL-08" : "Phek",
    "NL-09" : "Peren",
    "NL-10" : "Kiphire",
    "NL-11" : "Longleng",
    "NL-12" : "Pughoboto",
    "NL-13" : "Tseminyu",
    "NL-14" : "Chümoukedima",
    "NL-15" : "Niuland",
    "NL-16" : "Shamator",

# Odisa RTO Codes

    "OD-01" : "Balasore",
    "OD-02" : "Bhubaneswar",
    "OD-03" : "Balangir (Bolangir)",
    "OD-04" : "Chandikhole",
    "OD-05" : "Cuttack",
    "OD-06" : "Dhenkanal",
    "OD-07" : "Ganjam (Berhampur)",
    "OD-08" : "Kalahandi (Bhawanipatna)",
    "OD-09" : "Keonjhar",
    "OD-10" : "Koraput",
    "OD-11" : "Mayurbhanj (Baripada)",
    "OD-12" : "Phulbani (Kandhamal)",
    "OD-13" : "Puri",
    "OD-14" : "Rourkela",
    "OD-15" : "Sambalpur",
    "OD-16" : "Sundargarh",
    "OD-17" : "Bargarh",
    "OD-18" : "Rayagada",
    "OD-19" : "Angul",
    "OD-20" : "Gajapati",
    "OD-21" : "Jagatsinghpur",
    "OD-22" : "Bhadrak",
    "OD-23" : "Jharsuguda",
    "OD-24" : "Nabarangpur",
    "OD-25" : "Nayagarh",
    "OD-26" : "Nuapada",
    "OD-27" : "Boudh",
    "OD-28" : "Deogarh (Debagarh)",
    "OD-29" : "Kendrapara",
    "OD-30" : "Malkangiri",
    "OD-31" : "Subarnapur (Sonepur)",
    "OD-32" : "Bhanjanagar",
    "OD-33" : "Bhubaneswar-II",
    "OD-34" : "Jajpur",
    "OD-35" : "Talcher",

# Puducherry RTO Codes

    "PY-01" : "Puducherry",
    "PY-02" : "Karaikal",
    "PY-03" : "Mahe",
    "PY-04" : "Yanam",
    "PY-05" : "Oulgaret (Puducherry)",
    "PY-06" : "Kottucherry (Karaikal)",
    "PY-07" : "Nedungadu (Karaikal)",
    "PY-08" : "Bahour (Puducherry)",
    "PY-09" : "Villianur (Puducherry)",
    "PY-10" : "Tirunallar (Karaikal)",

# Sikkim RTO Codes

    "SK-01" : "Gangtok",
    "SK-02" : "Gyalshing (West Sikkim)",
    "SK-03" : "Mangan (North Sikkim)",
    "SK-04" : "Jorethang (South Sikkim)",
    "SK-05" : "Gangtok (East Sikkim)",
    "SK-06" : "Namchi (South Sikkim)",
    "SK-07" : "Pakyong",
    "SK-08" : "Soreng",

# Tamil Nadu RTO Codes

    "TN-01" : "Chennai Central",
    "TN-02" : "Chennai North-West",
    "TN-03" : "Chennai North-East",
    "TN-04" : "Chennai East",
    "TN-05" : "Chennai North",
    "TN-06" : "Chennai South-East",
    "TN-07" : "Chennai South",
    "TN-09" : "Chennai West",
    "TN-10" : "Chennai South-West",
    "TN-11" : "Tambaram",
    "TN-12" : "Poonamallee",
    "TN-18" : "Red Hills",
    "TN-19" : "Chengalpattu",
    "TN-20" : "Tiruvallur",
    "TN-21" : "Kanchipuram",
    "TN-22" : "Meenambakkam",
    "TN-23" : "Vellore",
    "TN-24" : "Krishnagiri",
    "TN-25" : "Tiruvannamalai",
    "TN-28" : "Namakkal",
    "TN-29" : "Dharmapuri",
    "TN-30" : "Salem West",
    "TN-31" : "Cuddalore",
    "TN-32" : "Villupuram",
    "TN-33" : "Erode",
    "TN-34" : "Thiruchengode",
    "TN-36" : "Gobichettipalayam",
    "TN-37" : "Coimbatore South",
    "TN-38" : "Coimbatore North",
    "TN-39" : "Tiruppur North",
    "TN-40" : "Mettupalayam",
    "TN-41" : "Pollachi",
    "TN-42" : "Tiruppur South",
    "TN-43" : "Ooty (Udhagamandalam)",
    "TN-45" : "Tiruchirappalli",
    "TN-46" : "Perambalur",
    "TN-47" : "Karur",
    "TN-48" : "Srirangam",
    "TN-49" : "Thanjavur",
    "TN-50" : "Tiruvarur",
    "TN-51" : "Nagapattinam",
    "TN-52" : "Sangagiri",
    "TN-54" : "Salem East",
    "TN-55" : "Pudukkottai",
    "TN-56" : "Perundurai",
    "TN-57" : "Dindigul",
    "TN-58" : "Madurai South",
    "TN-59" : "Madurai North",
    "TN-60" : "Theni",
    "TN-61" : "Ariyalur",
    "TN-63" : "Sivaganga",
    "TN-64" : "Madurai Central",
    "TN-65" : "Ramanathapuram",
    "TN-66" : "Coimbatore Central",
    "TN-67" : "Virudhunagar",
    "TN-68" : "Kumbakonam",
    "TN-69" : "Tuticorin (Thoothukudi)",
    "TN-70" : "Hosur",
    "TN-72" : "Tirunelveli",
    "TN-73" : "Ranipet",
    "TN-74" : "Nagercoil",
    "TN-75" : "Marthandam",
    "TN-76" : "Tenkasi",
    "TN-77" : "Attur",
    "TN-78" : "Dharapuram",
    "TN-79" : "Sankarankovil",
    "TN-81" : "Tiruchendur",
    "TN-82" : "Mayiladuthurai",
    "TN-83" : "Nagarkoil South",
    "TN-84" : "Srivilliputhur",
    "TN-86" : "Erode West",
    "TN-88" : "Namakkal South",
    "TN-90" : "Salem South",
    "TN-91" : "Chidambaram",
    "TN-92" : "Thiruvannamalai North",
    "TN-93" : "Mettur",
    "TN-94" : "Palani",
    "TN-95" : "Sivakasi",
    "TN-96" : "Kovilpatti",
    "TN-97" : "Arani",
    "TN-99" : "Coimbatore West",

# Tripura RTO Codes

    "TR-01" : "Agartala",
    "TR-02" : "Kailashahar",
    "TR-03" : "Udaipur",
    "TR-04" : "Dharmanagar",
    "TR-05" : "Ambassa",
    "TR-06" : "Khowai",
    "TR-07" : "Sepahijala",
    "TR-08" : "Santirbazar",
    "TR-09" : "Belonia",
    "TR-10" : "Kamalpur",

# Uttarakhand RTO Codes

    "UK-01" : "Almora",
    "UK-02" : "Bageshwar",
    "UK-03" : "Champawat",
    "UK-04" : "Nanital",
    "UK-05" : "Pithoragarh",
    "UK-06" : "Udham Singh Nagar",
    "UK-07" : "Dehradun",
    "UK-08" : "Haridwar",
    "UK-09" : "Tehri Garhwal",
    "UK-10" : "Uttarkashi",
    "UK-11" : "Chamoli Gopeshwar",
    "UK-12" : "Pauri Garhwal",
    "UK-13" : "Rudraprayag",
    "UK-14" : "Rishikesh",
    "UK-15" : "Kotdwar",
    "UK-16" : "Vikasnagar",
    "UK-17" : "Roorkee",
    "UK-18" : "Kashipur",
    "UK-19" : "Ramnagar",
    "UK-20" : "Ranikhet",

# West Bengal RTO Codes

    "WB-01" : "Kolkata Beltala",
    "WB-02" : "Kolkata Beltala",
    "WB-03" : "Kolkata Beltala",
    "WB-04" : "Kolkata Beltala",
    "WB-05" : "Kolkata Kasba",
    "WB-06" : "Kolkata Kasba",
    "WB-07" : "Kolkata Salt Lake",
    "WB-08" : "Kolkata Salt Lake",
    "WB-09" : "Behala",
    "WB-10" : "Not Allotted",
    "WB-11" : "Howrah",
    "WB-12" : "Howrah",
    "WB-13" : "Uluberia",
    "WB-14" : "Uluberia",
    "WB-15" : "Hooghly-Chinsurah",
    "WB-16" : "Hooghly-Chinsurah",
    "WB-17" : "Serampore",
    "WB-18" : "Arambagh / Dankuni region",
    "WB-19" : "Alipore",
    "WB-20" : "Alipore",
    "WB-21" : "Basirhat",
    "WB-22" : "Alipore",
    "WB-23" : "Barrackpore",
    "WB-24" : "Barrackpore",
    "WB-25" : "Barasat",
    "WB-26" : "Barasat",
    "WB-27" : "Bangaon",
    "WB-28" : "Bangaon",
    "WB-29" : "Tamluk",
    "WB-30" : "Tamluk",
    "WB-31" : "Contai",
    "WB-32" : "Contai / Haldia",
    "WB-33" : "Midnapore",
    "WB-34" : "Midnapore",
    "WB-35" : "Kharagpur",
    "WB-36" : "Midnapore",
    "WB-37" : "Asansol",
    "WB-38" : "Asansol",
    "WB-39" : "Durgapur",
    "WB-40" : "Durgapur",
    "WB-41" : "Burdwan",
    "WB-42" : "Burdwan",
    "WB-43" : "Kalna",
    "WB-44" : "Kalna / Asansol series",
    "WB-45" : "Rampurhat",
    "WB-46" : "Rampurhat",
    "WB-47" : "Bolpur",
    "WB-48" : "Bolpur",
    "WB-49" : "Jhargram",
    "WB-50" : "Ghatal / Jhargram",
    "WB-51" : "Nadia (Krishnanagar)",
    "WB-52" : "Tehatta",
    "WB-53" : "Birbhum",
    "WB-54" : "Birbhum",
    "WB-55" : "Purulia",
    "WB-56" : "Purulia",
    "WB-57" : "Murshidabad",
    "WB-58" : "Murshidabad",
    "WB-59" : "Raiganj",
    "WB-60" : "Raiganj",
    "WB-61" : "Balurghat",
    "WB-62" : "Balurghat",
    "WB-63" : "Cooch Behar",
    "WB-64" : "Cooch Behar",
    "WB-65" : "Malda",
    "WB-66" : "Malda",
    "WB-67" : "Bankura",
    "WB-68" : "Bankura",
    "WB-69" : "Alipurduar",
    "WB-70" : "Alipurduar",
    "WB-71" : "Jalpaiguri",
    "WB-72" : "Jalpaiguri",
    "WB-73" : "Siliguri",
    "WB-74" : "Siliguri",
    "WB-75" : "Katwa",
    "WB-76" : "Darjeeling",
    "WB-77" : "Darjeeling",
    "WB-78" : "Kalimpong",
    "WB-79" : "Kalimpong",
    "WB-80" : "Not Allotted",
    "WB-81" : "Raghunathpur",
    "WB-82" : "Raghunathpur",
    "WB-83" : "Chanchal",
    "WB-84" : "Chanchal",
    "WB-85" : "Mathabhanga",
    "WB-86" : "Mathabhanga",
    "WB-87" : "Bishnupur",
    "WB-88" : "Bishnupur",
    "WB-89" : "Kalyani",
    "WB-90" : "Kalyani",
    "WB-91" : "Islampur",
    "WB-92" : "Islampur",
    "WB-93" : "Jangipur",
    "WB-94" : "Jangipur",
    "WB-95" : "Baruipur",

# Chandigarh RTO Codes

    "CH-01" : "Chandigarh RTO",
    "CH-02" : "Chandigarh Registration Series",
    "CH-03" : "Chandigarh Registration Series",
    "CH-04" : "Chandigarh Registration Series",

# Lakshadweep RTO Codes

    "LD-01" : "Kavaratti",
    "LD-02" : "Agatti",
    "LD-03" : "Amini",
    "LD-04" : "Andrott",
    "LD-05" : "Kalpeni",
    "LD-06" : "Kiltan",
    "LD-07" : "Chetlat",
    "LD-08" : "Kadmat",
    "LD-09" : "Minicoy",

# Andaman and Nicobar Islands RTO Codes

    "AN-01" : "Port Blair (Capital)",
    "AN-02" : "Car Nicobar",
    "AN-03" : "Mayabunder",
    "AN-04" : "Diglipur"
}

# Printing length of RTO Codes

print(f"📚 Total RTO Codes Available : {len(rto)}")

# While loop is used to repeat the program until the user exits.

while True:
    print("Welcome to the Indian RTO Code Lookup!")
    print("Enter the RTO code (e.g., MH-01, DL-04) to find the corresponding location.")
    print("Type 'exit' to quit the program.")
    print("-------------------------------------------------------------")

# Taking input from user of RTO Code

    rto_code = input("Enter the RTO code: ").strip().upper()

    print("🔍 Searching...", end="", flush=True)

    for _ in range(2):
        time.sleep(0.3)
        print()

# Display output based on the user's input.

    if rto_code in rto:
        print("━━━━━━━━━━━━━━━━━━━━━━━━━━")
        print(f"✅ RTO Code : {rto_code}")
        print(f"📍 Location : {rto[rto_code]}")
        print("━━━━━━━━━━━━━━━━━━━━━━━━━━")
    else:
        print(Fore.RED + "❌ Invalid RTO Code!")
        print(Fore.YELLOW + "💡 Please Enter Code Like MH-01, DL-04, TG-09")
        print(Style.RESET_ALL)

    print(Fore.GREEN + "✔ Search Successful")
    print(Style.RESET_ALL)

    choice = input("Continue? (yes/no): ").strip().lower()

    if choice in ("no", "exit"):
        break

# Exit Message

print("\n" + "=" * 60)
print("🙏 Thank you for using Indian RTO Lookup System")
print("🚗 Drive Safe | Follow Traffic Rules")
print("=" * 60)

